spring.application.name=backend

server.port=8080
jwt.secret=my_super_secure_secret_key_1234567890
admin.registration.key=ParkIt_Admin_2026_x8Kp92LmQz
server.address=0.0.0.0
razorpay.key.id=rzp_test_SuM4awB90vRyr4
razorpay.key.secret=Yky9cT9SMe12O320l3jgi3cv


spring.datasource.url=jdbc:postgresql://localhost:5432/parkingdb
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

spring.jpa.open-in-view=false